# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 116d838a04f3ae2686b6d089003d99312be5ae230514e4ee1040ca698e43c965c76cd9b4bcacf478bfde5cedc5e573b7c8802959071b44622755993aa8e062b7

test:
  secret_key_base: a20538e07d9fa2654e47f0815c27988702c5dd54399bf9f874b22c16ee8242d68ebc06cb0ae630e3335e091a7ca2b72fd2b8d06ba7757a946a1ef5220053b6f6

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
